server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: IntelliEdu
  session:
    store-type: redis
    timeout: 2592000 # 30 days expiration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intelliedu
    username: root
    password: ${DEV_MYSQL_PASSWORD}
  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 5000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
openai:
  token: ${OPENAI_TOKEN}
